version: '3.9'

services:
  shoutoutai-knowledgebase-bot:
    build: .
    container_name: knowledgebase-bot
    ports:
      - "8501:8501"
    volumes:
      - "./knowledgebases:/app/knowledgebases"
